#!/usr/bin/python3

import socket
import smtplib
import os
import sys
import urllib2 
sender_address = "raspberrypilinuxesdios@gmail.com"
sender_password = "*******"
sender_server = 'smtp.gmail.com'
sender_port = 587
recipient_address = "linuxesdios@gmail.com"
def get_device_ip_address():

    try: 
        if os.name == "nt":
            # On Windows
            result = "Running on Windows"
            hostname = socket.gethostname()
            result += "\nHostname:  " + hostname
            host = socket.gethostbyname(hostname)
            result += "\nHost-IP-Address:" + host
            return result

        elif os.name == "posix":
            gw = os.popen("ip -4 route show default").read().split()
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.connect((gw[2], 0))
            ipaddr = s.getsockname()[0]
            gateway = gw[2]
            req = urllib2.Request('http://icanhazip.com', data=None)  
	    response = urllib2.urlopen(req, timeout=5)  
            IpPublic = (response.read())
	    result = "OS:\t\tRaspbian\nIP:\t\t" + ipaddr + "\nGateway:\t" + gateway + "\nIpPublica:\t\t" + IpPublic 
            return result
        
        else:
            result = os.name + " no funciona en este sistema."
            return result
    except:
        return "No detecta la IP"

def send_email(text):
    try:
        message = "From: " + sender_address + "\nTo: " + recipient_address + "\nSubject: Raspberry\n\n" + text 

        server = smtplib.SMTP(sender_server, sender_port)
        server.ehlo()
        server.starttls()
        server.login(sender_address, sender_password)
        server.sendmail(sender_address, recipient_address, message)
        server.close()
        print("Mensaje enviado por:\n", message)

    except:
        print("Fallo. Lee el punto 1 del tutorial.")

message = get_device_ip_address()
f = open ('holamundo.txt','r')
leido = f.read()
f.close()
if leido ==  message:
    print "No enviamos mensaje es igual"
else:
    print "Enviamos el mensaje ya que es distinto"
    send_email(message)
    print("mensaje enviado")
    f = open ('holamundo.txt','w')
    f.write(message)
    f.close()
sys.exit()
